- description: "Artifact Registry average daily repository size increased by 20%"
  metric_id: "artifactregistry.googleapis.com/repository/size"
  resource_type: "artifactregistry.googleapis.com/Repository"
  metric_kind: "GAUGE"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Artifact Registry average daily request count increased by 20%"
  metric_id: "artifactregistry.googleapis.com/repository/request_count"
  resource_type: "artifactregistry.googleapis.com/Repository"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Big Query average daily execution count increased by 20%"
  metric_id: "bigquery.googleapis.com/query/execution_count"
  resource_type: "bigquery_project"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Big Query average daily slots allocated increased by 20%"
  metric_id: "bigquery.googleapis.com/slots/allocated"
  resource_type: "bigquery_project"
  metric_kind: "GAUGE"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Budget average daily usage against quota limit increased by 10%"
  metric_id: "billingbudgets.googleapis.com/quota/budget_count/usage"
  resource_type: "billingbudgets.googleapis.com/Location"
  metric_kind: "GAUGE"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "10"
  aligners: 
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Certificate Manager average daily number of certificates increased by 20%"
  metric_id: "certificatemanager.googleapis.com/project/certificates"
  resource_type: "certificatemanager.googleapis.com/Project"
  metric_kind: "GAUGE"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Cloud Functions average daily execution count increased by 20%"
  metric_id: "cloudfunctions.googleapis.com/function/execution_count"
  resource_type: "cloud_function"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Cloud KMS average daily request count increased by 20%"
  metric_id: "cloudkms.googleapis.com/ekm/external/request_count"
  resource_type: "cloudkms.googleapis.com/Project"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Cloud SQL database is not up / available"
  metric_id: "cloudsql.googleapis.com/database/up"
  resource_type: "cloudsql_database"
  metric_kind: "GAUGE"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_LT"
  duration: "60s"
  threshold: "1"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Composer average daily usage time increased by 20%"
  metric_id: "composer.googleapis.com/workload/cpu/usage_time"
  resource_type: "internal_composer_workload"
  metric_kind: "DELTA"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Google Compute Engine CPU utilization over 80% for 51% of the day"
  metric_id: "compute.googleapis.com/instance/cpu/utilization"
  resource_type: "gce_instance"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "43200s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Google Compute Engine RAM utilization over 80% for 51% of the day"
  metric_id: "agent.googleapis.com/memory/percent_used"
  resource_type: "gce_instance"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "43200s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Google Compute Engine DISK utilization over 80% for 51% of the day"
  metric_id: "agent.googleapis.com/disk/percent_used"
  resource_type: "gce_instance"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "43200s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Google Compute Engine OS uptime longer than 30 days"
  metric_id: "compute.googleapis.com/instance/uptime_total"
  resource_type: "gce_instance"
  metric_kind: "GAUGE"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "2592000" #30 days in seconds
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Dataflow aggregated work utilization over 80%"
  metric_id: "dataflow.googleapis.com/job/aggregated_worker_utilization"
  resource_type: "dataflow_job"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Dataproc average completion time increased by 20%"
  metric_id: "dataproc.googleapis.com/cluster/job/completion_time"
  resource_type: "cloud_dataproc_cluster"
  metric_kind: "DELTA"
  value_type: "DISTRIBUTION"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_SUM"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_MEAN"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Filestore used bytes above 80%"
  metric_id: "file.googleapis.com/nfs/server/used_bytes_percent"
  resource_type: "filestore_instance"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Google Kubernetes Engine CPU utilization over 80% for 51% of the day"
  metric_id: "kubernetes.io/container/cpu/limit_utilization"
  resource_type: "k8s_container"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "43200s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Google Kubernetes Engine RAM utilization over 80% for 51% of the day"
  metric_id: "kubernetes.io/container/memory/limit_utilization"
  resource_type: "k8s_container"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "43200s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Google Kubernetes Engine DISK utilization over 80% for 51% of the day"
  metric_id: "kubernetes.io/pod/volume/utilization"
  resource_type: "k8s_pod"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "43200s"
  threshold: "80"
  aligners: 
  - aligner: "ALIGN_NONE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "IAM average daily authentication request count increased by 20%"
  metric_id: "iam.googleapis.com/service_account/authn_events_count"
  resource_type: "iam_service_account"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Load Balancer average daily request count increased by 20%"
  metric_id: "loadbalancing.googleapis.com/https/request_count"
  resource_type: "https_lb_rule"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Network Connectivity active VPC spokes increases / decreased by 20%"
  metric_id: "networkconnectivity.googleapis.com/quota/active_vpc_spokes_per_hub/usage"
  resource_type: "networkconnectivity.googleapis.com/Hub"
  metric_kind: "GAUGE"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Networking average daily router egress packet count changed by 20%"
  metric_id: "networking.googleapis.com/router_appliance/gateway/egress_bytes_count"
  resource_type: "gce_instance"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Networking average daily router ingress packet count changed by 20%"
  metric_id: "networking.googleapis.com/router_appliance/gateway/ingress_bytes_count"
  resource_type: "gce_instance"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Networking average daily VPN Tunnel egress packet count changed by 20%"
  metric_id: "networking.googleapis.com/vpn_tunnel/egress_bytes_count"
  resource_type: "vpn_tunnel"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Networking average daily VPN Tunnel ingress packet count changed by 20%"
  metric_id: "networking.googleapis.com/vpn_tunnel/ingress_bytes_count"
  resource_type: "vpn_tunnel"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Networking VPN tunnel no longer active" #based on dropped package count percent change
  metric_id: "vpn.googleapis.com/network/dropped_sent_packets_count"
  resource_type: "vpn_gateway"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "60s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Network Security average daily ingress packet count changed by 20%"
  metric_id: "networksecurity.googleapis.com/dos/ingress_packets_count"
  resource_type: "networksecurity.googleapis.com/ProtectedEndpoint"
  metric_kind: "DELTA"
  value_type: "INT64"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_RATE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"

- description: "Oracle Database average daily transaction count increased / decreased by 20%"
  metric_id: "oracledatabase.googleapis.com/containerdatabase/transactions"
  resource_type: "oracledatabase.googleapis.com/ContainerDatabase"
  metric_kind: "GAUGE"
  value_type: "DOUBLE"
  severity: "warning"
  comparison: "COMPARISON_GT"
  duration: "60s"
  threshold: "20"
  aligners: 
  - aligner: "ALIGN_PERCENT_CHANGE"
    alignment_period: "86400s"
    cross_series_reducer: "REDUCE_NONE"
  documentation: "documentation"
